### Sign In
POST http://localhost:3000/v1/auth/sign-in
Content-Type: application/json

{
    "username": "admin_user",
    "password": "Password123!@#"
}

# Response:
# {
#   "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
#   "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
# }

### Create Reimbursement
POST http://localhost:3000/v1/reimbursement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlkyUE1WQTJUR0ZBQjBZN0IyWlBFSlNUIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTA0NTcyMzQsImlhdCI6MTc1MDQ1MzYzNH0.mAvCjvepJZJ6h8A0bhhf_IcfNDpya0uaSFnBWFIy4fc

{
    "amount": 100000,
    "description": "Reimbursement for travel expenses"
}

# Response:
# {
#   "ok": true,
# }

### Create Attendance
POST http://localhost:3000/v1/attendance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlkyUE1WQTJUR0ZBQjBZN0IyWlBFSlNUIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTA0NTMyNTEsImlhdCI6MTc1MDQ0OTY1MX0.kn1D72aiXLoQ9K5UmcBbE_Zz445-m-8qWLXJV8lSKJo

{
    "start_time": "2025-06-18T08:00:00Z",
    "end_time": "2025-06-18T08:00:01Z"
}

# Response:
# {
#   "ok": true,
# }

### Create Overtime
POST http://localhost:3000/v1/overtime
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlkyUE1WQTJUR0ZBQjBZN0IyWlBFSlNUIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTA0NTcyMzQsImlhdCI6MTc1MDQ1MzYzNH0.mAvCjvepJZJ6h8A0bhhf_IcfNDpya0uaSFnBWFIy4fc

{
    "date": "2025-06-18",
    "total_hours": 1
}

# Response:
# {
#   "ok": true,
# }

### Create Payroll Period
POST http://localhost:3000/v1/payroll/period
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlkyUE1WOVhBQjdaTldESDIzRDFWSlQwIiwiaXNfYWRtaW4iOnRydWUsImV4cCI6MTc1MDQ2MDA3NiwiaWF0IjoxNzUwNDU2NDc2fQ.oBoc58g7kpG0Wr7baQ7BbqFmEnZP_BjPabLzbQCDiTg

{
    "start_date": "2025-06-20",
    "end_date": "2025-06-21"
}

# Response:
# {
#   "ok": true,
# }


### List Payroll Period(With Pagination)
GET http://localhost:3000/v1/payroll/period?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlkyUE1WOVhBQjdaTldESDIzRDFWSlQwIiwiaXNfYWRtaW4iOnRydWUsImV4cCI6MTc1MDQ2NDUzMywiaWF0IjoxNzUwNDYwOTMzfQ.xSJK8NzfC0YbzEnSaRSFxYbvAGZu4enWRw3aAEd_Nyo

# Response:
# {
#   "ok": true,
#   "data": [
#     {
#       "id": "01JY7PQRVBZVVMGAN0FQXDQ1B1",
#       "start_date": "2025-06-20T00:00:00Z",
#       "end_date": "2025-06-21T00:00:00Z",
#       "is_generated": false,
#       "created_at": "2025-06-21T05:18:21.931273+07:00",
#       "created_by": "01JY2PMV9XAB7ZNWDH23D1VJT0",
#       "updated_at": "2025-06-21T05:18:21.992274+07:00",
#       "updated_by": null
#     },
#   ],
#   "paging": {
#     "page": 1,
#     "page_size": 10,
#     "total_item": 1,
#     "total_page": 1
#   }
# }
